import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type ElementType } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { ArrowLeft, Bell, CalendarDays, CarFront, Check, ChevronRight, FileBarChart, IndianRupee, LayoutDashboard, Megaphone, Pencil, Plus, Settings, Store, Tags, TentTree, Trash2, Users, WalletCards, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { BrandLogo } from "@/components/brand-logo";
import { RoleGate } from "@/components/role-gate";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/admin")({
  head: () => ({ meta: [
    { title: "Admin Dashboard | My Tento" },
    { name: "description", content: "Manage My Tento bookings, providers, users, payments and offers." },
    { property: "og:title", content: "Admin Dashboard | My Tento" },
    { property: "og:description", content: "Manage My Tento operations." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: () => <RoleGate role="admin"><AdminPanel /></RoleGate>,
});

type Tab = "overview" | "services" | "providers" | "bookings" | "users" | "payments" | "offers" | "cab" | "content" | "notifications" | "reports" | "settings";

const adminNavigation: Array<{ id: Tab; label: string; icon: ElementType }> = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "services", label: "Services", icon: Tags },
  { id: "providers", label: "Providers", icon: Store },
  { id: "bookings", label: "Bookings", icon: CalendarDays },
  { id: "users", label: "Customers", icon: Users },
  { id: "payments", label: "Payments", icon: WalletCards },
  { id: "offers", label: "Offers", icon: Megaphone },
  { id: "cab", label: "Cab control", icon: CarFront },
  { id: "content", label: "Banners", icon: TentTree },
  { id: "notifications", label: "Notifications", icon: Bell },
  { id: "reports", label: "Reports", icon: FileBarChart },
  { id: "settings", label: "Settings", icon: Settings },
];

const adminSectionCopy: Record<Tab, { title: string; sub: string }> = {
  overview: { title: "Platform overview", sub: "Monitor live MyTento operations" },
  services: { title: "Services", sub: "Manage listings shown to customers" },
  providers: { title: "Providers", sub: "Review and verify provider records" },
  bookings: { title: "Bookings", sub: "Track all saved customer bookings" },
  users: { title: "Customers", sub: "View registered customer profiles" },
  payments: { title: "Payments", sub: "Review saved payment records" },
  offers: { title: "Offers", sub: "Control live discount codes" },
  cab: { title: "Cab control", sub: "Manage live vehicle records and rates" },
  content: { title: "Banners", sub: "Manage offers, updates and announcements" },
  notifications: { title: "Notifications", sub: "Live data only" },
  reports: { title: "Reports", sub: "Live data only" },
  settings: { title: "Settings", sub: "Live data only" },
};

type ServiceForm = { id?: string; providerId: string; businessName: string; description: string; phone: string; city: string; area: string; distance: string; serviceId: string; price: string; details: string; active: boolean };
const emptyServiceForm: ServiceForm = { providerId: "new", businessName: "", description: "", phone: "", city: "Lucknow", area: "", distance: "5", serviceId: "", price: "", details: "", active: true };

function AdminPanel() {
  const [tab, setTab] = useState<Tab>("overview");
  const [serviceDialog, setServiceDialog] = useState(false);
  const [serviceForm, setServiceForm] = useState<ServiceForm>(emptyServiceForm);
  const [savingService, setSavingService] = useState(false);
  const queryClient = useQueryClient();
  const { data: providers = [] } = useQuery({ queryKey: ["admin-providers"], queryFn: async () => { const { data, error } = await supabase.from("providers").select("id,business_name,description,city,rating,verified,active").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: bookings = [] } = useQuery({ queryKey: ["admin-bookings"], queryFn: async () => { const { data, error } = await supabase.from("bookings").select("id,booking_code,booking_type,event_date,event_time,city,total_amount,status,providers(business_name)").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: profiles = [] } = useQuery({ queryKey: ["admin-users"], queryFn: async () => { const [{ data, error }, { data: adminRoles }] = await Promise.all([supabase.from("profiles").select("id,full_name,phone,city").order("created_at", { ascending: false }), supabase.from("user_roles").select("user_id").eq("role", "admin")]); if (error) throw error; const adminIds = new Set((adminRoles ?? []).map((role) => role.user_id)); return (data ?? []).filter((profile) => !adminIds.has(profile.id)); } });
  const { data: payments = [] } = useQuery({ queryKey: ["admin-payments"], queryFn: async () => { const { data, error } = await supabase.from("payments").select("id,method,amount,status,created_at,bookings(booking_code)").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: offers = [] } = useQuery({ queryKey: ["admin-offers"], queryFn: async () => { const { data, error } = await supabase.from("offers").select("id,code,title,discount_percent,max_discount,active").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: vehicles = [] } = useQuery({ queryKey: ["admin-vehicles"], queryFn: async () => { const { data, error } = await supabase.from("vehicles").select("id,vehicle_type,vehicle_number,seats,base_fare,per_km_rate,active,providers(business_name)").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: banners = [] } = useQuery({ queryKey: ["admin-banners"], queryFn: async () => { const { data, error } = await supabase.from("banners").select("id,banner_type,title,subtitle,active,sort_order").order("sort_order"); if (error) throw error; return data ?? []; } });
  const { data: serviceCategories = [] } = useQuery({ queryKey: ["admin-service-categories"], queryFn: async () => { const { data, error } = await supabase.from("services").select("id,name,active").order("sort_order"); if (error) throw error; return data ?? []; } });
  const { data: providerServices = [] } = useQuery({ queryKey: ["admin-provider-services"], queryFn: async () => { const { data, error } = await supabase.from("provider_services").select("id,provider_id,service_id,base_price,details,active,providers(business_name,description,phone,city,area,distance_km),services(name)").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const toggleProvider = async (id: string, verified: boolean) => { const { error } = await supabase.from("providers").update({ verified: !verified }).eq("id", id); if (error) { toast.error("Provider could not be updated"); return; } await queryClient.invalidateQueries({ queryKey: ["admin-providers"] }); toast.success("Provider updated"); };
  const toggleOffer = async (id: string, active: boolean) => { const { error } = await supabase.from("offers").update({ active: !active }).eq("id", id); if (error) { toast.error("Offer could not be updated"); return; } await queryClient.invalidateQueries({ queryKey: ["admin-offers"] }); };
  const toggleVehicle = async (id: string, active: boolean) => { const { error } = await supabase.from("vehicles").update({ active: !active }).eq("id", id); if (error) { toast.error("Vehicle could not be updated"); return; } await queryClient.invalidateQueries({ queryKey: ["admin-vehicles"] }); };
  const openNewService = () => { setServiceForm({ ...emptyServiceForm, serviceId: serviceCategories[0]?.id ?? "" }); setServiceDialog(true); };
  const openEditService = (item: (typeof providerServices)[number]) => { const provider = Array.isArray(item.providers) ? item.providers[0] : item.providers; setServiceForm({ id: item.id, providerId: item.provider_id, businessName: provider?.business_name ?? "", description: provider?.description ?? "", phone: provider?.phone ?? "", city: provider?.city ?? "Lucknow", area: provider?.area ?? "", distance: String(provider?.distance_km ?? 5), serviceId: item.service_id, price: String(item.base_price), details: item.details, active: item.active }); setServiceDialog(true); };
  const saveService = async () => { if (!serviceForm.serviceId || !serviceForm.price || (!serviceForm.id && !serviceForm.businessName.trim())) { toast.error("Provider, service and price are required"); return; } setSavingService(true); try { let providerId = serviceForm.providerId; if (serviceForm.id) { const { error: providerError } = await supabase.from("providers").update({ business_name: serviceForm.businessName.trim(), description: serviceForm.description.trim(), phone: serviceForm.phone.trim(), city: serviceForm.city.trim(), area: serviceForm.area.trim(), distance_km: Number(serviceForm.distance), verified: true, active: true }).eq("id", providerId); if (providerError) throw providerError; const { error } = await supabase.from("provider_services").update({ service_id: serviceForm.serviceId, base_price: Number(serviceForm.price), details: serviceForm.details.trim(), active: serviceForm.active }).eq("id", serviceForm.id); if (error) throw error; } else { const { data: provider, error: providerError } = await supabase.from("providers").insert({ business_name: serviceForm.businessName.trim(), description: serviceForm.description.trim(), phone: serviceForm.phone.trim(), city: serviceForm.city.trim(), area: serviceForm.area.trim(), distance_km: Number(serviceForm.distance), verified: true, active: true }).select("id").single(); if (providerError) throw providerError; providerId = provider.id; const { error } = await supabase.from("provider_services").insert({ provider_id: providerId, service_id: serviceForm.serviceId, base_price: Number(serviceForm.price), details: serviceForm.details.trim(), active: serviceForm.active }); if (error) throw error; } await Promise.all([queryClient.invalidateQueries({ queryKey: ["admin-provider-services"] }), queryClient.invalidateQueries({ queryKey: ["admin-providers"] }), queryClient.invalidateQueries({ queryKey: ["providers"] })]); setServiceDialog(false); toast.success(serviceForm.id ? "Service updated" : "Service added"); } catch { toast.error("Service could not be saved"); } finally { setSavingService(false); } };
  const toggleService = async (id: string, active: boolean) => { const { error } = await supabase.from("provider_services").update({ active: !active }).eq("id", id); if (error) { toast.error("Service could not be updated"); return; } await Promise.all([queryClient.invalidateQueries({ queryKey: ["admin-provider-services"] }), queryClient.invalidateQueries({ queryKey: ["providers"] })]); };
  const deleteService = async (id: string) => { if (!window.confirm("Delete this service listing?")) return; const { error } = await supabase.from("provider_services").delete().eq("id", id); if (error) { toast.error("Service could not be deleted"); return; } await Promise.all([queryClient.invalidateQueries({ queryKey: ["admin-provider-services"] }), queryClient.invalidateQueries({ queryKey: ["providers"] })]); toast.success("Service deleted"); };
  const revenue = payments.filter((item) => item.status === "paid" || item.status === "advance_paid").reduce((sum, item) => sum + Number(item.amount), 0);
  const go = (next: Tab) => { setTab(next); window.scrollTo(0, 0); };
  const currentSection = adminSectionCopy[tab];
  return <div className="min-h-svh min-w-0 overflow-x-clip bg-muted/40">
    <header className="safe-top sticky top-0 z-30 border-b border-border/70 bg-card/95 backdrop-blur lg:hidden"><div className="grid min-h-16 grid-cols-[minmax(0,1fr)_auto] items-center px-3 py-2 sm:px-6"><Button variant="ghost" asChild className="h-auto min-w-0 justify-start gap-2 px-0 hover:bg-transparent"><Link to="/"><ArrowLeft className="size-5 shrink-0" /><BrandLogo priority className="size-11" /><span className="truncate font-display text-lg font-extrabold text-logo">MyTento <span className="text-xs text-muted-foreground">Admin</span></span></Link></Button></div><div className="flex gap-1 overflow-x-auto px-3 sm:px-6">{adminNavigation.map(({ id, label }) => <Button key={id} variant="ghost" size="sm" onClick={() => go(id)} className={`shrink-0 rounded-none border-b-2 ${tab === id ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>{label}</Button>)}</div></header>
    <div className="mx-auto flex min-h-svh w-full max-w-[1600px]">
      <aside className="sticky top-0 hidden h-svh w-64 shrink-0 flex-col border-r border-border bg-card lg:flex">
        <div className="border-b border-border px-5 py-5"><Button variant="ghost" asChild className="h-auto w-full justify-start gap-3 px-0 hover:bg-transparent"><Link to="/"><BrandLogo priority className="size-12" /><span className="min-w-0 text-left"><span className="block truncate font-display text-xl font-extrabold text-logo">MyTento</span><span className="block text-xs font-semibold text-muted-foreground">Administration</span></span></Link></Button></div>
        <nav aria-label="Admin navigation" className="flex-1 space-y-1 overflow-y-auto p-3">{adminNavigation.map(({ id, label, icon: Icon }) => <Button key={id} variant="ghost" onClick={() => go(id)} className={`h-11 w-full justify-start gap-3 px-3 ${tab === id ? "bg-primary text-primary-foreground hover:bg-primary/90 hover:text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="size-5 shrink-0" /><span className="flex-1 text-left">{label}</span>{tab === id && <ChevronRight className="size-4 shrink-0" />}</Button>)}</nav>
        <div className="border-t border-border p-4"><Button variant="outline" asChild className="w-full justify-start gap-2"><Link to="/"><ArrowLeft className="size-4" /> Back to customer app</Link></Button></div>
      </aside>
      <div className="min-w-0 flex-1">
        <div className="hidden min-h-24 items-center justify-between border-b border-border bg-card px-8 lg:flex xl:px-10"><div><p className="text-xs font-bold uppercase text-primary">MyTento Admin</p><h1 className="mt-1 text-2xl font-extrabold">{currentSection.title}</h1><p className="mt-1 text-sm text-muted-foreground">{currentSection.sub}</p></div><div className="rounded-md border border-border bg-muted/60 px-3 py-2 text-right"><p className="text-xs font-semibold text-muted-foreground">Live workspace</p><p className="text-sm font-bold text-success">Connected</p></div></div>
    <main className="w-full px-4 py-6 sm:px-6 lg:px-8 lg:py-8 xl:px-10">
      {tab === "overview" && <><Page title="Platform overview" sub="Live MyTento operations" /><div className="grid grid-cols-2 gap-3 md:grid-cols-4 lg:gap-5"><Stat icon={CalendarDays} label="Bookings" value={String(bookings.length)} /><Stat icon={Store} label="Active providers" value={String(providers.filter((p) => p.active).length)} /><Stat icon={IndianRupee} label="Recorded payments" value={`₹${revenue.toLocaleString("en-IN")}`} /><Stat icon={Users} label="Users" value={String(profiles.length)} /></div><div className="grid gap-7 xl:grid-cols-[minmax(0,1.5fr)_minmax(280px,0.8fr)]"><Section title="Latest bookings">{bookings.length === 0 ? <Empty text="No bookings yet." /> : bookings.slice(0,5).map((booking) => <BookingRow key={booking.id} booking={booking} />)}</Section><Section title="Provider status">{providers.length === 0 ? <Empty text="No providers registered." /> : providers.slice(0,5).map((provider) => <Card key={provider.id}><div className="flex items-center gap-3"><Avatar text={provider.business_name} /><div className="min-w-0 flex-1"><b className="block truncate">{provider.business_name}</b><p className="text-xs text-muted-foreground">{provider.city} · {provider.verified ? "Verified" : "Awaiting verification"}</p></div></div></Card>)}</Section></div></>}
      {tab === "services" && <><div className="mb-6 flex items-end justify-between gap-3"><Page title="Services" sub="Live provider listings shown to customers" /><Button onClick={openNewService}><Plus className="size-4" /> Add service</Button></div><ListEmpty count={providerServices.length} text="No service listings yet.">{providerServices.map((item) => { const provider = Array.isArray(item.providers) ? item.providers[0] : item.providers; const category = Array.isArray(item.services) ? item.services[0] : item.services; return <Card key={item.id}><div className="flex flex-wrap items-center gap-3"><div className="min-w-0 flex-1"><b>{provider?.business_name ?? "Provider"}</b><p className="text-xs text-muted-foreground">{category?.name} · ₹{Number(item.base_price).toLocaleString("en-IN")} · {item.details}</p></div><Button size="sm" variant={item.active ? "default" : "outline"} onClick={() => void toggleService(item.id, item.active)}>{item.active ? "Active" : "Paused"}</Button><Button size="icon" variant="outline" aria-label="Edit service" onClick={() => openEditService(item)}><Pencil className="size-4" /></Button><Button size="icon" variant="outline" aria-label="Delete service" onClick={() => void deleteService(item.id)} className="text-destructive"><Trash2 className="size-4" /></Button></div></Card>; })}</ListEmpty></>}
      {tab === "providers" && <><Page title="Providers" sub="Live provider records" /><ListEmpty count={providers.length} text="No providers registered.">{providers.map((provider) => <Card key={provider.id}><div className="flex items-center gap-3"><Avatar text={provider.business_name} /><div className="min-w-0 flex-1"><b>{provider.business_name}</b><p className="text-xs text-muted-foreground">{provider.city} · ★ {Number(provider.rating).toFixed(1)}</p></div><Button size="sm" variant={provider.verified ? "outline" : "default"} onClick={() => void toggleProvider(provider.id, provider.verified)}>{provider.verified ? <><Check className="size-4" /> Verified</> : <><X className="size-4" /> Verify</>}</Button></div></Card>)}</ListEmpty></>}
      {tab === "bookings" && <><Page title="Bookings" sub="All saved customer bookings" /><ListEmpty count={bookings.length} text="No bookings yet.">{bookings.map((booking) => <BookingRow key={booking.id} booking={booking} />)}</ListEmpty></>}
      {tab === "users" && <><Page title="Users" sub="Registered customer profiles" /><ListEmpty count={profiles.length} text="No user profiles yet.">{profiles.map((profile) => <Card key={profile.id}><div className="flex items-center gap-3"><Avatar text={profile.full_name || "User"} /><div className="min-w-0"><b>{profile.full_name || "Unnamed user"}</b><p className="text-xs text-muted-foreground">{profile.phone || "No phone"} · {profile.city || "No city"}</p></div></div></Card>)}</ListEmpty></>}
      {tab === "payments" && <><Page title="Payments" sub="Saved payment records" /><ListEmpty count={payments.length} text="No payments yet.">{payments.map((payment) => { const booking = Array.isArray(payment.bookings) ? payment.bookings[0] : payment.bookings; return <Card key={payment.id}><div className="flex items-center gap-3"><IndianRupee className="size-5 text-primary" /><div className="min-w-0 flex-1"><b>{booking?.booking_code ?? payment.id}</b><p className="text-xs text-muted-foreground">{payment.method} · {payment.status}</p></div><b className="text-primary">₹{Number(payment.amount).toLocaleString("en-IN")}</b></div></Card>; })}</ListEmpty></>}
      {tab === "offers" && <><Page title="Offers" sub="Live discount codes" /><ListEmpty count={offers.length} text="No offers created.">{offers.map((offer) => <Card key={offer.id}><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><b>{offer.code}</b><p className="text-xs text-muted-foreground">{offer.title} · {offer.discount_percent}% off</p></div><Button size="sm" variant={offer.active ? "default" : "outline"} onClick={() => void toggleOffer(offer.id, offer.active)}>{offer.active ? "Active" : "Paused"}</Button></div></Card>)}</ListEmpty></>}
      {tab === "cab" && <><Page title="Cab control" sub="Live vehicle records and rates" /><ListEmpty count={vehicles.length} text="No vehicles registered.">{vehicles.map((vehicle) => { const provider = Array.isArray(vehicle.providers) ? vehicle.providers[0] : vehicle.providers; return <Card key={vehicle.id}><div className="flex items-center gap-3"><TentTree className="size-5 text-primary" /><div className="min-w-0 flex-1"><b>{vehicle.vehicle_type} · {vehicle.vehicle_number}</b><p className="text-xs text-muted-foreground">{provider?.business_name ?? "Unassigned"} · ₹{Number(vehicle.base_fare)}/base · ₹{Number(vehicle.per_km_rate)}/km</p></div><Button size="sm" variant={vehicle.active ? "default" : "outline"} onClick={() => void toggleVehicle(vehicle.id, vehicle.active)}>{vehicle.active ? "Active" : "Paused"}</Button></div></Card>; })}</ListEmpty></>}
      {tab === "content" && <><Page title="Banners" sub="Live offers, updates and announcements" /><ListEmpty count={banners.length} text="No banners created.">{banners.map((banner) => <Card key={banner.id}><b>{banner.title}</b><p className="text-xs text-muted-foreground">{banner.banner_type} · {banner.subtitle} · {banner.active ? "Active" : "Paused"}</p></Card>)}</ListEmpty></>}
      {(["notifications","reports","settings"] as Tab[]).includes(tab) && <><Page title={tab[0]?.toUpperCase() + tab.slice(1)} sub="Live data only" /><Empty text="No live records or controls are available here yet." /></>}
    </main>
      </div>
    </div>
    <Dialog open={serviceDialog} onOpenChange={setServiceDialog}><DialogContent className="max-h-[90svh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>{serviceForm.id ? "Edit service" : "Add service"}</DialogTitle><DialogDescription>Changes are saved to the live database and reflected in customer search.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><FieldInput label="Provider name" value={serviceForm.businessName} onChange={(businessName) => setServiceForm((form) => ({ ...form, businessName }))} /><FieldInput label="Phone" value={serviceForm.phone} onChange={(phone) => setServiceForm((form) => ({ ...form, phone }))} /><FieldInput label="City" value={serviceForm.city} onChange={(city) => setServiceForm((form) => ({ ...form, city }))} /><FieldInput label="Area" value={serviceForm.area} onChange={(area) => setServiceForm((form) => ({ ...form, area }))} /><FieldInput label="Distance (km)" type="number" value={serviceForm.distance} onChange={(distance) => setServiceForm((form) => ({ ...form, distance }))} /><FieldInput label="Price" type="number" value={serviceForm.price} onChange={(price) => setServiceForm((form) => ({ ...form, price }))} /><label className="grid gap-2"><Label>Category</Label><select aria-label="Service category" value={serviceForm.serviceId} onChange={(event) => setServiceForm((form) => ({ ...form, serviceId: event.target.value }))} className="h-9 rounded-md border border-input bg-background px-3 text-sm">{serviceCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="flex items-end gap-2 pb-2"><input type="checkbox" checked={serviceForm.active} onChange={(event) => setServiceForm((form) => ({ ...form, active: event.target.checked }))} /><span className="text-sm font-medium">Active listing</span></label><div className="sm:col-span-2"><FieldInput label="Provider description" value={serviceForm.description} onChange={(description) => setServiceForm((form) => ({ ...form, description }))} /></div><div className="sm:col-span-2"><FieldInput label="Service details" value={serviceForm.details} onChange={(details) => setServiceForm((form) => ({ ...form, details }))} /></div></div><DialogFooter><Button variant="outline" onClick={() => setServiceDialog(false)}>Cancel</Button><Button disabled={savingService} onClick={() => void saveService()}>{savingService ? "Saving…" : "Save service"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function BookingRow({ booking }: { booking: { booking_code: string; booking_type: string; event_date: string; event_time: string; total_amount: number; status: string; providers: { business_name: string } | { business_name: string }[] | null } }) { const provider = Array.isArray(booking.providers) ? booking.providers[0] : booking.providers; return <Card><div className="flex items-center gap-3"><TentTree className="size-5 text-primary" /><div className="min-w-0 flex-1"><b>{booking.booking_type} · {booking.booking_code}</b><p className="text-xs text-muted-foreground">{provider?.business_name || "Unassigned"} · {booking.event_date} {booking.event_time}</p></div><div className="text-right"><b className="text-primary">₹{Number(booking.total_amount).toLocaleString("en-IN")}</b><p className="text-xs capitalize text-muted-foreground">{booking.status.replaceAll("_", " ")}</p></div></div></Card>; }
function Page({ title, sub }: { title: string; sub: string }) { return <div className="mb-6 lg:hidden"><h1 className="text-2xl font-extrabold">{title}</h1><p className="text-sm text-muted-foreground">{sub}</p></div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7 min-w-0"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">{title}</h2></div><div className="space-y-3">{children}</div></section>; }
function Card({ children }: { children: React.ReactNode }) { return <div className="min-w-0 rounded-lg border border-border bg-card p-4 shadow-sm">{children}</div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-lg border border-border bg-card p-5 text-sm text-muted-foreground">{text}</p>; }
function ListEmpty({ count, text, children }: { count: number; text: string; children: React.ReactNode }) { return count === 0 ? <Empty text={text} /> : <div className="grid min-w-0 gap-3 xl:grid-cols-2">{children}</div>; }
function Avatar({ text }: { text: string }) { return <span className="grid size-11 shrink-0 place-items-center rounded-lg bg-brand-soft font-bold text-primary">{text.split(/\s+/).slice(0,2).map((part) => part[0]).join("").toUpperCase()}</span>; }
function Stat({ icon: Icon, label, value }: { icon: ElementType; label: string; value: string }) { return <div className="rounded-lg border border-border bg-card p-4 shadow-sm lg:p-5"><span className="grid size-10 place-items-center rounded-md bg-brand-soft"><Icon className="size-5 text-primary" /></span><p className="mt-4 break-words font-display text-xl font-extrabold lg:text-2xl">{value}</p><p className="mt-1 text-xs font-medium text-muted-foreground">{label}</p></div>; }
function FieldInput({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-2"><Label>{label}</Label><Input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }