import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type ElementType } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { ArrowLeft, CalendarDays, Check, IndianRupee, Store, TentTree, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BrandLogo } from "@/components/brand-logo";
import { RoleGate } from "@/components/role-gate";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/admin")({
  head: () => ({ meta: [
    { title: "Admin Dashboard | My Tento" },
    { name: "description", content: "Manage My Tento bookings, providers, users, payments and offers." },
    { property: "og:title", content: "Admin Dashboard | My Tento" },
    { property: "og:description", content: "Manage My Tento operations." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: () => <RoleGate role="admin"><AdminPanel /></RoleGate>,
});

type Tab = "overview" | "providers" | "bookings" | "users" | "payments" | "offers" | "cab" | "content" | "notifications" | "reports" | "settings";

function AdminPanel() {
  const [tab, setTab] = useState<Tab>("overview");
  const queryClient = useQueryClient();
  const { data: providers = [] } = useQuery({ queryKey: ["admin-providers"], queryFn: async () => { const { data, error } = await supabase.from("providers").select("id,business_name,description,city,rating,verified,active").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: bookings = [] } = useQuery({ queryKey: ["admin-bookings"], queryFn: async () => { const { data, error } = await supabase.from("bookings").select("id,booking_code,booking_type,event_date,event_time,city,total_amount,status,providers(business_name)").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: profiles = [] } = useQuery({ queryKey: ["admin-users"], queryFn: async () => { const { data, error } = await supabase.from("profiles").select("id,full_name,phone,city").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: payments = [] } = useQuery({ queryKey: ["admin-payments"], queryFn: async () => { const { data, error } = await supabase.from("payments").select("id,method,amount,status,created_at,bookings(booking_code)").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: offers = [] } = useQuery({ queryKey: ["admin-offers"], queryFn: async () => { const { data, error } = await supabase.from("offers").select("id,code,title,discount_percent,max_discount,active").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: vehicles = [] } = useQuery({ queryKey: ["admin-vehicles"], queryFn: async () => { const { data, error } = await supabase.from("vehicles").select("id,vehicle_type,vehicle_number,seats,base_fare,per_km_rate,active,providers(business_name)").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const { data: banners = [] } = useQuery({ queryKey: ["admin-banners"], queryFn: async () => { const { data, error } = await supabase.from("banners").select("id,banner_type,title,subtitle,active,sort_order").order("sort_order"); if (error) throw error; return data ?? []; } });
  const toggleProvider = async (id: string, verified: boolean) => { const { error } = await supabase.from("providers").update({ verified: !verified }).eq("id", id); if (error) { toast.error("Provider could not be updated"); return; } await queryClient.invalidateQueries({ queryKey: ["admin-providers"] }); toast.success("Provider updated"); };
  const toggleOffer = async (id: string, active: boolean) => { const { error } = await supabase.from("offers").update({ active: !active }).eq("id", id); if (error) { toast.error("Offer could not be updated"); return; } await queryClient.invalidateQueries({ queryKey: ["admin-offers"] }); };
  const toggleVehicle = async (id: string, active: boolean) => { const { error } = await supabase.from("vehicles").update({ active: !active }).eq("id", id); if (error) { toast.error("Vehicle could not be updated"); return; } await queryClient.invalidateQueries({ queryKey: ["admin-vehicles"] }); };
  const revenue = payments.filter((item) => item.status === "paid" || item.status === "advance_paid").reduce((sum, item) => sum + Number(item.amount), 0);
  const go = (next: Tab) => { setTab(next); window.scrollTo(0, 0); };
  return <div className="min-h-svh min-w-0 overflow-x-clip bg-background">
    <header className="safe-top sticky top-0 z-30 border-b border-border/70 bg-card/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-6xl items-center px-3 py-2 sm:px-6"><Button variant="ghost" asChild className="h-auto min-w-0 justify-start gap-2 px-0 hover:bg-transparent"><Link to="/"><ArrowLeft className="size-5" /><BrandLogo priority className="size-11" /><span className="truncate font-display text-lg font-extrabold text-logo">MyTento <span className="text-xs text-muted-foreground">Admin</span></span></Link></Button></div><div className="mx-auto flex max-w-6xl gap-1 overflow-x-auto px-3 sm:px-6">{(["overview","providers","bookings","users","payments","offers","cab","content","notifications","reports","settings"] as Tab[]).map((id) => <Button key={id} variant="ghost" size="sm" onClick={() => go(id)} className={`shrink-0 capitalize ${tab === id ? "border-b-2 border-primary text-primary" : "text-muted-foreground"}`}>{id === "content" ? "Banners" : id}</Button>)}</div></header>
    <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6">
      {tab === "overview" && <><Page title="Platform overview" sub="Live MyTento operations" /><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={CalendarDays} label="Bookings" value={String(bookings.length)} /><Stat icon={Store} label="Active providers" value={String(providers.filter((p) => p.active).length)} /><Stat icon={IndianRupee} label="Recorded payments" value={`₹${revenue.toLocaleString("en-IN")}`} /><Stat icon={Users} label="Users" value={String(profiles.length)} /></div><Section title="Latest bookings">{bookings.length === 0 ? <Empty text="No bookings yet." /> : bookings.slice(0,5).map((booking) => <BookingRow key={booking.id} booking={booking} />)}</Section></>}
      {tab === "providers" && <><Page title="Providers" sub="Live provider records" /><ListEmpty count={providers.length} text="No providers registered.">{providers.map((provider) => <Card key={provider.id}><div className="flex items-center gap-3"><Avatar text={provider.business_name} /><div className="min-w-0 flex-1"><b>{provider.business_name}</b><p className="text-xs text-muted-foreground">{provider.city} · ★ {Number(provider.rating).toFixed(1)}</p></div><Button size="sm" variant={provider.verified ? "outline" : "default"} onClick={() => void toggleProvider(provider.id, provider.verified)}>{provider.verified ? <><Check className="size-4" /> Verified</> : <><X className="size-4" /> Verify</>}</Button></div></Card>)}</ListEmpty></>}
      {tab === "bookings" && <><Page title="Bookings" sub="All saved customer bookings" /><ListEmpty count={bookings.length} text="No bookings yet.">{bookings.map((booking) => <BookingRow key={booking.id} booking={booking} />)}</ListEmpty></>}
      {tab === "users" && <><Page title="Users" sub="Registered customer profiles" /><ListEmpty count={profiles.length} text="No user profiles yet.">{profiles.map((profile) => <Card key={profile.id}><div className="flex items-center gap-3"><Avatar text={profile.full_name || "User"} /><div className="min-w-0"><b>{profile.full_name || "Unnamed user"}</b><p className="text-xs text-muted-foreground">{profile.phone || "No phone"} · {profile.city || "No city"}</p></div></div></Card>)}</ListEmpty></>}
      {tab === "payments" && <><Page title="Payments" sub="Saved payment records" /><ListEmpty count={payments.length} text="No payments yet.">{payments.map((payment) => { const booking = Array.isArray(payment.bookings) ? payment.bookings[0] : payment.bookings; return <Card key={payment.id}><div className="flex items-center gap-3"><IndianRupee className="size-5 text-primary" /><div className="min-w-0 flex-1"><b>{booking?.booking_code ?? payment.id}</b><p className="text-xs text-muted-foreground">{payment.method} · {payment.status}</p></div><b className="text-primary">₹{Number(payment.amount).toLocaleString("en-IN")}</b></div></Card>; })}</ListEmpty></>}
      {tab === "offers" && <><Page title="Offers" sub="Live discount codes" /><ListEmpty count={offers.length} text="No offers created.">{offers.map((offer) => <Card key={offer.id}><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><b>{offer.code}</b><p className="text-xs text-muted-foreground">{offer.title} · {offer.discount_percent}% off</p></div><Button size="sm" variant={offer.active ? "default" : "outline"} onClick={() => void toggleOffer(offer.id, offer.active)}>{offer.active ? "Active" : "Paused"}</Button></div></Card>)}</ListEmpty></>}
      {tab === "cab" && <><Page title="Cab control" sub="Live vehicle records and rates" /><ListEmpty count={vehicles.length} text="No vehicles registered.">{vehicles.map((vehicle) => { const provider = Array.isArray(vehicle.providers) ? vehicle.providers[0] : vehicle.providers; return <Card key={vehicle.id}><div className="flex items-center gap-3"><TentTree className="size-5 text-primary" /><div className="min-w-0 flex-1"><b>{vehicle.vehicle_type} · {vehicle.vehicle_number}</b><p className="text-xs text-muted-foreground">{provider?.business_name ?? "Unassigned"} · ₹{Number(vehicle.base_fare)}/base · ₹{Number(vehicle.per_km_rate)}/km</p></div><Button size="sm" variant={vehicle.active ? "default" : "outline"} onClick={() => void toggleVehicle(vehicle.id, vehicle.active)}>{vehicle.active ? "Active" : "Paused"}</Button></div></Card>; })}</ListEmpty></>}
      {tab === "content" && <><Page title="Banners" sub="Live offers, updates and announcements" /><ListEmpty count={banners.length} text="No banners created.">{banners.map((banner) => <Card key={banner.id}><b>{banner.title}</b><p className="text-xs text-muted-foreground">{banner.banner_type} · {banner.subtitle} · {banner.active ? "Active" : "Paused"}</p></Card>)}</ListEmpty></>}
      {(["notifications","reports","settings"] as Tab[]).includes(tab) && <><Page title={tab[0]?.toUpperCase() + tab.slice(1)} sub="Live data only" /><Empty text="No live records or controls are available here yet." /></>}
    </main>
  </div>;
}

function BookingRow({ booking }: { booking: { booking_code: string; booking_type: string; event_date: string; event_time: string; total_amount: number; status: string; providers: { business_name: string } | { business_name: string }[] | null } }) { const provider = Array.isArray(booking.providers) ? booking.providers[0] : booking.providers; return <Card><div className="flex items-center gap-3"><TentTree className="size-5 text-primary" /><div className="min-w-0 flex-1"><b>{booking.booking_type} · {booking.booking_code}</b><p className="text-xs text-muted-foreground">{provider?.business_name || "Unassigned"} · {booking.event_date} {booking.event_time}</p></div><div className="text-right"><b className="text-primary">₹{Number(booking.total_amount).toLocaleString("en-IN")}</b><p className="text-xs capitalize text-muted-foreground">{booking.status.replaceAll("_", " ")}</p></div></div></Card>; }
function Page({ title, sub }: { title: string; sub: string }) { return <div className="mb-6"><h1 className="text-2xl font-extrabold">{title}</h1><p className="text-sm text-muted-foreground">{sub}</p></div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7"><h2 className="mb-3 font-bold">{title}</h2><div className="space-y-3">{children}</div></section>; }
function Card({ children }: { children: React.ReactNode }) { return <div className="rounded-lg border border-border bg-card p-4">{children}</div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-lg border border-border bg-card p-5 text-sm text-muted-foreground">{text}</p>; }
function ListEmpty({ count, text, children }: { count: number; text: string; children: React.ReactNode }) { return count === 0 ? <Empty text={text} /> : <div className="space-y-3">{children}</div>; }
function Avatar({ text }: { text: string }) { return <span className="grid size-11 shrink-0 place-items-center rounded-lg bg-brand-soft font-bold text-primary">{text.split(/\s+/).slice(0,2).map((part) => part[0]).join("").toUpperCase()}</span>; }
function Stat({ icon: Icon, label, value }: { icon: ElementType; label: string; value: string }) { return <div className="rounded-lg border border-border bg-card p-4"><Icon className="size-5 text-primary" /><p className="mt-3 break-words font-display text-xl font-extrabold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>; }