import { useQuery } from "@tanstack/react-query";
import { Car, ChevronRight, MapPin, Navigation } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";

export type AdminExtraTab = "content" | "notifications" | "reports" | "settings";

export function CabPriorityCard({ onOpen }: { onOpen: () => void }) {
  return <section className="mb-6 flex min-w-0 items-center justify-between gap-3 rounded-3xl bg-festive p-4"><div className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white/15 text-white"><Navigation className="size-5" /></span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-widest text-white/70">Need a ride?</p><h2 className="truncate font-display text-sm font-bold text-white">View nearby vehicles</h2></div></div><Button onClick={onOpen} variant="ghost" className="shrink-0 rounded-xl bg-white/15 px-4 text-xs font-bold text-white hover:bg-white/25">View <ChevronRight className="size-4" /></Button></section>;
}

export function ClientCabScreen() {
  const { data: vehicles = [], isLoading } = useQuery({ queryKey: ["public-vehicles"], queryFn: async () => { const { data, error } = await supabase.from("vehicles").select("id,vehicle_type,seats,base_fare,per_km_rate,providers(id,business_name,city,distance_km,verified,active)").eq("active", true).order("base_fare"); if (error) throw error; return (data ?? []).filter((vehicle) => { const provider = Array.isArray(vehicle.providers) ? vehicle.providers[0] : vehicle.providers; return provider?.active && provider.verified && Number(provider.distance_km) <= 10; }); } });
  return <div className="min-w-0 animate-rise-in"><div className="rounded-b-[28px] bg-primary px-5 pb-6 pt-4 text-primary-foreground"><p className="text-[10px] font-black uppercase text-accent">Cab booking</p><h1 className="mt-1 font-display text-2xl font-extrabold">Nearby vehicles</h1><p className="mt-1 text-xs text-primary-foreground/75">Only active vehicles from verified providers within 10 km</p></div><div className="space-y-4 px-4 pt-5">{isLoading ? <p className="text-sm text-muted-foreground">Loading vehicles…</p> : vehicles.length === 0 ? <p className="rounded-lg border border-border bg-card p-5 text-sm text-muted-foreground">No verified cab vehicles are available nearby right now.</p> : vehicles.map((vehicle) => { const provider = Array.isArray(vehicle.providers) ? vehicle.providers[0] : vehicle.providers; return <div key={vehicle.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-start gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-lg bg-secondary text-primary"><Car className="size-6" /></span><div className="min-w-0 flex-1"><h2 className="font-bold">{vehicle.vehicle_type}</h2><p className="text-xs text-muted-foreground">{vehicle.seats} seats · {provider?.business_name}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3" /> {provider?.city} · {Number(provider?.distance_km).toFixed(1)} km</p></div><div className="text-right"><p className="font-bold text-primary">₹{Number(vehicle.base_fare)}</p><p className="text-[10px] text-muted-foreground">+ ₹{Number(vehicle.per_km_rate)}/km</p></div></div></div>; })}</div></div>;
}