import { useMemo, useState } from "react";
import {
  Bell, CalendarClock, Camera, Car, Check, ChevronRight, CircleDollarSign, Clock3,
  ImagePlus, MapPin, Minus, Navigation, Phone, Plus, RotateCcw, Save, Settings,
  ShieldCheck, Star, Store, Trash2, Truck, Upload, UserRound, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import vehicleCab from "@/assets/vehicle-cab.webp";
import vehicleSuv from "@/assets/vehicle-suv.webp";
import vehicleAuto from "@/assets/vehicle-auto.webp";
import packageBasic from "@/assets/package-basic.webp";
import packageStandard from "@/assets/package-standard.webp";
import packagePremium from "@/assets/package-premium.webp";
import homeBanner from "@/assets/home-banner.webp";

type CabStage = "search" | "driver" | "tracking";
type Vehicle = { name: string; seats: string; base: number; perKm: number; eta: string; image: string };

const vehicles: Vehicle[] = [
  { name: "Car", seats: "4 seats", base: 80, perKm: 14, eta: "3 min", image: vehicleCab },
  { name: "SUV", seats: "6 seats", base: 130, perKm: 20, eta: "5 min", image: vehicleSuv },
  { name: "Scorpio", seats: "7 seats", base: 180, perKm: 24, eta: "7 min", image: vehicleSuv },
  { name: "Cruiser", seats: "12 seats", base: 280, perKm: 32, eta: "10 min", image: vehicleSuv },
  { name: "Truckon", seats: "Goods", base: 350, perKm: 38, eta: "12 min", image: vehicleAuto },
];

export function CabPriorityCard({ onOpen }: { onOpen: () => void }) {
  return <section className="mb-6 flex min-w-0 items-center justify-between gap-3 rounded-3xl bg-festive p-4">
    <div className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white/15 text-white"><Navigation className="size-5" /></span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-widest text-white/70">Need a ride?</p><h2 className="truncate font-display text-sm font-bold text-white">Cab Quick Booking</h2></div></div>
    <Button onClick={onOpen} variant="ghost" className="shrink-0 rounded-xl bg-white/15 px-4 text-xs font-bold text-white hover:bg-white/25">Book <ChevronRight className="size-4" /></Button>
  </section>;
}

export function ClientCabScreen() {
  const [stage, setStage] = useState<CabStage>("search");
  const [pickup, setPickup] = useState("Gomti Nagar, Lucknow");
  const [drop, setDrop] = useState("Charbagh Railway Station, Lucknow");
  const [vehicle, setVehicle] = useState("Car");
  const [count, setCount] = useState(1);
  const [distance, setDistance] = useState(8.4);
  const [status, setStatus] = useState(1);
  const [cancelled, setCancelled] = useState(false);
  const [reschedule, setReschedule] = useState(false);
  const selected = vehicles.find((item) => item.name === vehicle) ?? vehicles[0];
  const fare = selected ? Math.round((selected.base + selected.perKm * distance) * count) : 0;
  const field = "w-full rounded-lg border border-border bg-card p-3 text-sm outline-none focus:border-primary";
  if (stage !== "search") return <CabTripPanel stage={stage} setStage={setStage} vehicle={vehicle} count={count} fare={fare} status={status} setStatus={setStatus} cancelled={cancelled} setCancelled={setCancelled} reschedule={reschedule} setReschedule={setReschedule} />;

  return <div className="min-w-0 animate-rise-in">
    <div className="rounded-b-[28px] bg-primary px-5 pb-6 pt-4 text-primary-foreground"><p className="text-[10px] font-black uppercase text-accent">Cab · first priority</p><h1 className="mt-1 font-display text-2xl font-extrabold">Book your ride</h1><p className="mt-1 text-xs text-primary-foreground/75">Location-wise cabs with transparent distance fares</p></div>
    <div className="space-y-5 px-4 pt-5">
      <div className="rounded-xl border border-border bg-card p-4 shadow-sm"><label className="text-xs font-bold"><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-success" />Pickup location</span><input aria-label="Cab pickup" value={pickup} onChange={(e) => setPickup(e.target.value)} className={`mt-2 ${field}`} /></label><div className="my-2 ml-1 h-4 border-l border-dashed border-border" /><label className="text-xs font-bold"><span className="flex items-center gap-2"><MapPin className="size-3 text-accent" />Drop location</span><input aria-label="Cab destination" value={drop} onChange={(e) => setDrop(e.target.value)} className={`mt-2 ${field}`} /></label></div>
      <section><div className="flex items-end justify-between"><div><h2 className="font-bold">Nearby vehicles</h2><p className="text-xs text-muted-foreground">5 types available near {pickup.split(",")[0]}</p></div><span className="text-xs font-bold text-success">● Live</span></div><div className="-mx-1 mt-3 flex gap-2 overflow-x-auto px-1 pb-2">{vehicles.map((item) => <Button key={item.name} variant="outline" onClick={() => setVehicle(item.name)} className={`h-auto min-w-28 flex-col p-2 ${vehicle === item.name ? "border-primary bg-secondary ring-2 ring-primary/15" : ""}`}><img src={item.image} alt={item.name} className="h-12 w-full object-contain" /><span className="text-xs font-bold">{item.name}</span><span className="text-[9px] text-muted-foreground">{item.seats} · {item.eta}</span></Button>)}</div></section>
      <div className="grid grid-cols-2 gap-3"><label className="rounded-lg border border-border bg-card p-3"><span className="text-[10px] font-bold uppercase text-muted-foreground">Vehicles needed</span><span className="mt-2 flex items-center justify-between"><Button size="icon" variant="outline" aria-label="Remove vehicle" className="size-8" onClick={() => setCount(Math.max(1, count - 1))}><Minus className="size-3" /></Button><b>{count}</b><Button size="icon" aria-label="Add vehicle" className="size-8" onClick={() => setCount(Math.min(10, count + 1))}><Plus className="size-3" /></Button></span></label><label className="rounded-lg border border-border bg-card p-3"><span className="text-[10px] font-bold uppercase text-muted-foreground">Distance</span><select aria-label="Trip distance" value={distance} onChange={(e) => setDistance(Number(e.target.value))} className="mt-2 w-full bg-transparent text-sm font-bold outline-none"><option value={8.4}>8.4 km</option><option value={15}>15 km</option><option value={28}>28 km</option><option value={50}>50 km</option></select></label></div>
      <section className="rounded-xl border border-border bg-card p-4"><div className="mb-3 flex justify-between"><div><h2 className="font-bold">Fare list</h2><p className="text-xs text-muted-foreground">Base fare + price per km</p></div><CircleDollarSign className="text-primary" /></div>{vehicles.map((item) => <button key={item.name} onClick={() => setVehicle(item.name)} className={`flex w-full items-center justify-between border-t border-border py-2 text-left text-xs ${vehicle === item.name ? "font-bold text-primary" : ""}`}><span>{item.name} · ₹{item.perKm}/km</span><span>₹{Math.round((item.base + item.perKm * distance) * count).toLocaleString("en-IN")}</span></button>)}<div className="mt-2 flex items-center justify-between rounded-lg bg-secondary p-3"><span className="text-xs font-bold">Estimated total</span><span className="font-display text-xl font-extrabold text-primary">₹{fare.toLocaleString("en-IN")}</span></div></section>
      <Button size="lg" className="w-full" onClick={() => setStage("driver")}><Car className="size-4" /> Confirm {vehicle} <ChevronRight className="size-4" /></Button>
    </div>
  </div>;
}

function CabTripPanel({ stage, setStage, vehicle, count, fare, status, setStatus, cancelled, setCancelled, reschedule, setReschedule }: { stage: CabStage; setStage: (v: CabStage) => void; vehicle: string; count: number; fare: number; status: number; setStatus: (v: number) => void; cancelled: boolean; setCancelled: (v: boolean) => void; reschedule: boolean; setReschedule: (v: boolean) => void }) {
  const tripSteps = ["Driver assigned", "Driver arriving", "Ride started", "Destination reached"];
  return <div className="min-w-0 animate-rise-in"><div className="relative h-52 overflow-hidden rounded-xl bg-brand-soft"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(var(--border)_1px,transparent_1px),linear-gradient(90deg,var(--border)_1px,transparent_1px)] [background-size:28px_28px]" /><div className="absolute left-8 top-8 grid size-9 place-items-center rounded-full bg-success text-primary-foreground shadow-lg"><MapPin className="size-4" /></div><div className="absolute bottom-10 right-10 grid size-11 place-items-center rounded-full bg-primary text-primary-foreground shadow-action"><Car className="size-5" /></div><div className="absolute left-12 top-14 h-24 w-56 max-w-[70%] rotate-6 rounded-[50%] border-b-4 border-dashed border-primary" /><span className="absolute bottom-3 left-3 rounded-full bg-card px-3 py-1 text-xs font-bold text-primary">Live route · 8 min away</span></div>
    <div className="mt-4 rounded-xl border border-border bg-card p-4"><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-secondary font-bold text-primary">RK</span><div className="min-w-0"><p className="font-bold">Ravi Kumar</p><p className="break-words text-xs text-muted-foreground">{vehicle} · UP 32 MN 4821 · <Star className="inline size-3 fill-accent text-accent" /> 4.9</p></div><Button size="icon" asChild><a href="tel:+919415012345" aria-label="Call driver"><Phone className="size-4" /></a></Button></div><div className="mt-3 grid grid-cols-1 gap-2 rounded-lg bg-muted p-3 text-center text-xs min-[340px]:grid-cols-3"><span><b className="block">{count}</b>vehicle</span><span><b className="block">₹{fare}</b>fare</span><span><b className="block">8 min</b>ETA</span></div></div>
    <div className="mt-4 rounded-xl border border-border bg-card p-4"><h2 className="font-bold">Live tracking</h2><div className="mt-4 space-y-3">{tripSteps.map((item, i) => <div key={item} className="flex items-center gap-3"><span className={`grid size-7 place-items-center rounded-full ${i <= status ? "bg-success text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{i < status ? <Check className="size-4" /> : i + 1}</span><span className={`text-sm font-semibold ${i <= status ? "" : "text-muted-foreground"}`}>{item}</span></div>)}</div>{!cancelled && <Button variant="outline" className="mt-4 w-full" disabled={status === 3} onClick={() => { setStatus(Math.min(3, status + 1)); setStage("tracking"); }}>{status === 3 ? "Trip completed" : "Simulate next live update"}</Button>}</div>
    {reschedule && !cancelled && <label className="mt-4 block rounded-xl border border-border bg-card p-4 text-sm font-bold">New pickup time<input aria-label="Rescheduled pickup time" type="datetime-local" defaultValue="2026-12-25T19:00" className="mt-2 w-full rounded-md border border-border bg-background p-3 font-normal" /><Button className="mt-3 w-full" onClick={() => setReschedule(false)}><Save className="size-4" /> Save new schedule</Button></label>}
    {cancelled ? <div className="mt-4 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm font-bold text-destructive">Booking cancelled. Refund status will appear in Wallet.</div> : <div className="mt-4 grid grid-cols-1 gap-3 min-[340px]:grid-cols-2"><Button variant="outline" onClick={() => setReschedule(!reschedule)}><CalendarClock className="size-4" /> Reschedule</Button><Button variant="outline" className="text-destructive" onClick={() => setCancelled(true)}><X className="size-4" /> Cancel ride</Button></div>}
  </div>;
}

type TentItem = { id: number; name: string; price: number; image: string; active: boolean };
const starterTents: TentItem[] = [
  { id: 1, name: "Normal Tent", price: 12000, image: packageBasic, active: true },
  { id: 2, name: "Modern Tent", price: 18000, image: packageStandard, active: true },
  { id: 3, name: "Golden Tent", price: 25000, image: packagePremium, active: true },
  { id: 4, name: "Royal Tent", price: 30000, image: homeBanner, active: true },
];

export function ProviderInventoryManager() {
  const [logoMode, setLogoMode] = useState<"inner" | "outer">("outer");
  const [items, setItems] = useState(starterTents);
  const [gadgets, setGadgets] = useState([{ name: "DJ setup", price: 6000 }, { name: "Night & gate lights", price: 3500 }, { name: "Decoration", price: 4000 }]);
  const [newName, setNewName] = useState(""); const [newPrice, setNewPrice] = useState(""); const [saved, setSaved] = useState(false);
  const updatePrice = (id: number, price: number) => setItems((list) => list.map((item) => item.id === id ? { ...item, price } : item));
  const add = () => { const price = Number(newPrice); if (!newName.trim() || !Number.isFinite(price) || price <= 0) return; setItems((list) => [...list, { id: Date.now(), name: newName.trim(), price, image: packageStandard, active: true }]); setNewName(""); setNewPrice(""); };
  return <div className="animate-rise-in"><h1 className="text-2xl font-extrabold">Store profile & inventory</h1><p className="text-sm text-muted-foreground">Manage logo, tent posts, gadgets and customer prices</p>
    <section className="relative mt-5 overflow-hidden rounded-xl"><img src={homeBanner} alt="Royal Tent House cover" className="h-44 w-full object-cover min-[360px]:h-36" /><div className="absolute inset-0 bg-gradient-to-t from-primary/90 to-transparent" /><div className="absolute bottom-3 left-3 flex max-w-[calc(100%-1.5rem)] items-end gap-3"><span className="grid size-14 shrink-0 place-items-center rounded-xl border-4 border-card bg-primary font-display text-lg font-extrabold text-primary-foreground min-[360px]:size-16">RT</span><div className="min-w-0 pb-1 text-primary-foreground"><b className="block truncate">Royal Tent House</b><p className="truncate text-[10px]">Outer banner + inner profile logo</p></div></div><Button size="sm" className="absolute right-3 top-3 max-w-[calc(100%-1.5rem)] bg-card px-2 text-primary min-[360px]:px-3" onClick={() => setLogoMode(logoMode === "outer" ? "inner" : "outer")}><Camera className="size-4" /> Edit {logoMode} logo</Button></section>
    <section className="mt-6"><div className="flex items-end justify-between"><div><h2 className="font-bold">Tent posts & rates</h2><p className="text-xs text-muted-foreground">Photo and price shown to customers</p></div><span className="text-xs font-bold text-success">{items.filter((i) => i.active).length} live</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{items.map((item) => <div key={item.id} className="overflow-hidden rounded-xl border border-border bg-card"><img src={item.image} alt={item.name} className="h-28 w-full object-cover" /><div className="p-3"><div className="flex items-center justify-between"><input aria-label={`${item.name} name`} value={item.name} onChange={(e) => setItems((list) => list.map((x) => x.id === item.id ? { ...x, name: e.target.value } : x))} className="min-w-0 flex-1 bg-transparent text-sm font-bold outline-none" /><Button size="icon" variant="ghost" aria-label={`Toggle ${item.name}`} onClick={() => setItems((list) => list.map((x) => x.id === item.id ? { ...x, active: !x.active } : x))}>{item.active ? <Check className="size-4 text-success" /> : <X className="size-4" />}</Button></div><label className="mt-2 flex items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm"><span>₹</span><input aria-label={`${item.name} price`} type="number" value={item.price} onChange={(e) => updatePrice(item.id, Number(e.target.value))} className="w-full bg-transparent font-bold outline-none" /></label></div></div>)}</div></section>
    <section className="mt-6 rounded-xl border border-border bg-card p-4"><h2 className="font-bold">Create tent post</h2><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_140px_auto]"><input aria-label="New tent name" value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="Tent name" className="rounded-md border border-border bg-background p-3 text-sm" /><input aria-label="New tent price" type="number" value={newPrice} onChange={(e) => setNewPrice(e.target.value)} placeholder="Price ₹" className="rounded-md border border-border bg-background p-3 text-sm" /><Button onClick={add}><ImagePlus className="size-4" /> Add</Button></div><p className="mt-2 text-xs text-muted-foreground">The entered price is saved with the new tent post.</p></section>
    <section className="mt-6"><h2 className="font-bold">Available gadgets</h2><div className="mt-3 space-y-2">{gadgets.map((g, index) => <div key={`${g.name}-${index}`} className="grid grid-cols-[minmax(0,1fr)_auto_auto_auto] items-center gap-2 rounded-lg border border-border bg-card p-3"><input aria-label={`Gadget ${index + 1}`} value={g.name} onChange={(e) => setGadgets((list) => list.map((x, n) => n === index ? { ...x, name: e.target.value } : x))} className="min-w-0 bg-transparent text-sm font-bold outline-none" /><span className="text-sm">₹</span><input aria-label={`${g.name} rate`} type="number" value={g.price} onChange={(e) => setGadgets((list) => list.map((x, n) => n === index ? { ...x, price: Number(e.target.value) } : x))} className="w-16 bg-transparent text-sm font-bold outline-none min-[360px]:w-20" /><Button size="icon" variant="ghost" onClick={() => setGadgets((list) => list.filter((_, n) => n !== index))}><Trash2 className="size-4" /></Button></div>)}</div><div className="mt-2 grid grid-cols-1 gap-2 min-[360px]:grid-cols-[minmax(0,1fr)_6.25rem_auto]"><input id="gadget-name" placeholder="Custom gadget" className="min-w-0 rounded-md border border-border bg-background p-2 text-sm" /><input id="gadget-price" placeholder="₹ rate" type="number" className="min-w-0 rounded-md border border-border bg-background p-2 text-sm" /><Button variant="outline" onClick={() => { const n = document.getElementById("gadget-name") as HTMLInputElement | null; const p = document.getElementById("gadget-price") as HTMLInputElement | null; if (n?.value && p?.value) { setGadgets((list) => [...list, { name: n.value, price: Number(p.value) }]); n.value = ""; p.value = ""; } }}><Plus className="size-4" /> <span className="min-[360px]:hidden">Add gadget</span></Button></div></section>
    <Button className="mt-6" onClick={() => setSaved(true)}>{saved ? <><Check className="size-4" /> All changes saved</> : <><Save className="size-4" /> Save profile & rates</>}</Button>
  </div>;
}

export type AdminExtraTab = "content" | "notifications" | "reports" | "settings";
export function AdminRequirementCenter({ tab }: { tab: AdminExtraTab }) {
  const [saved, setSaved] = useState(false); const [audience, setAudience] = useState("Customer"); const [period, setPeriod] = useState("Daily");
  const report = useMemo(() => period === "Daily" ? ["42", "₹1.28L", "8"] : period === "Weekly" ? ["286", "₹8.9L", "51"] : ["1,284", "₹38.4L", "214"], [period]);
  if (tab === "content") return <div className="animate-rise-in"><Page title="Home banners & provider photos" sub="Manage artwork shown across the app" /><div className="overflow-hidden rounded-xl border border-border bg-card"><img src={homeBanner} alt="Current home banner" className="h-48 w-full object-cover" /><div className="grid gap-3 p-4 min-[380px]:grid-cols-[minmax(0,1fr)_auto] min-[380px]:items-center"><div className="min-w-0"><b className="break-words">Wedding season banner</b><p className="text-xs text-muted-foreground">Active on customer home</p></div><Button onClick={() => setSaved(true)} className="w-full min-[380px]:w-auto"><Upload className="size-4" /> {saved ? "Banner updated" : "Change banner"}</Button></div></div><h2 className="mb-3 mt-6 font-bold">Provider profile pictures</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{["RT", "ST", "CE", "GC"].map((x) => <button key={x} className="rounded-xl border border-border bg-card p-4 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-brand-soft font-bold text-primary">{x}</span><span className="mt-2 block text-xs font-bold">Edit photo</span></button>)}</div></div>;
  if (tab === "notifications") return <div className="animate-rise-in"><Page title="Notifications" sub="Separate messages for every app role" /><div className="grid grid-cols-1 gap-2 min-[340px]:grid-cols-3">{["Customer", "Provider", "Admin"].map((x) => <Button key={x} variant={audience === x ? "default" : "outline"} onClick={() => setAudience(x)}>{x}</Button>)}</div><div className="mt-4 rounded-xl border border-border bg-card p-4"><label className="text-xs font-bold">Message title<input aria-label="Notification title" defaultValue={`${audience} update`} className="mt-2 w-full rounded-md border border-border bg-background p-3 text-sm" /></label><label className="mt-3 block text-xs font-bold">Message<textarea aria-label="Notification message" defaultValue="Your MyTento booking has a new update." rows={4} className="mt-2 w-full rounded-md border border-border bg-background p-3 text-sm" /></label><Button className="mt-3 w-full" onClick={() => setSaved(true)}><Bell className="size-4" /> {saved ? `Sent to ${audience}s` : `Send to ${audience}s`}</Button></div></div>;
  if (tab === "reports") return <div className="animate-rise-in"><Page title="Reports" sub="Daily, weekly and monthly performance" /><div className="grid grid-cols-1 gap-2 min-[340px]:grid-cols-3">{["Daily", "Weekly", "Monthly"].map((x) => <Button key={x} variant={period === x ? "default" : "outline"} onClick={() => setPeriod(x)}>{x}</Button>)}</div><div className="mt-5 grid grid-cols-1 gap-3 min-[340px]:grid-cols-3">{[["Bookings", report[0]], ["Revenue", report[1]], ["Providers", report[2]]].map(([a,b]) => <div key={a} className="rounded-xl border border-border bg-card p-4"><p className="break-words font-display text-lg font-extrabold text-primary min-[360px]:text-xl">{b}</p><p className="text-xs text-muted-foreground">{a}</p></div>)}</div><div className="mt-5 rounded-xl border border-border bg-card p-3 min-[360px]:p-5"><div className="flex h-44 items-end gap-2 min-[360px]:gap-3">{[42,66,54,83,71,92,76].map((h,i) => <div key={i} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><div className="w-full rounded-t bg-primary" style={{height:`${h}%`}} /><span className="text-[9px] text-muted-foreground">{i+1}</span></div>)}</div></div></div>;
  return <div className="animate-rise-in"><Page title="App settings" sub="Banner, offers and platform controls" /><div className="space-y-3">{[["Customer bookings", "Allow new bookings"], ["Provider registration", "Accept new providers"], ["Cash payment", "Allow cash to provider"]].map(([a,b]) => <label key={a} className="flex items-center gap-3 rounded-xl border border-border bg-card p-4"><Settings className="size-5 text-primary" /><span className="flex-1"><b className="block text-sm">{a}</b><span className="text-xs text-muted-foreground">{b}</span></span><input type="checkbox" defaultChecked className="size-5 accent-primary" /></label>)}</div><div className="mt-5 rounded-xl border border-border bg-card p-4"><h2 className="font-bold">Quick offer</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label="Offer code" placeholder="Offer code" className="rounded-md border border-border bg-background p-3 text-sm" /><input aria-label="Offer discount" placeholder="Discount %" type="number" className="rounded-md border border-border bg-background p-3 text-sm" /></div><Button className="mt-3" onClick={() => setSaved(true)}><Plus className="size-4" /> {saved ? "Offer added" : "Add offer"}</Button></div></div>;
}

function Page({ title, sub }: { title: string; sub: string }) { return <div className="mb-6"><h1 className="text-2xl font-extrabold">{title}</h1><p className="text-sm text-muted-foreground">{sub}</p></div>; }